### ISSUE TITLE
Big black men kissing appear on my screen every so often 

### ISSUE THREAD

**Issue by Thatsaltyboi** [TylerPalko/gamehub#2]
Very annoying :/

**Comment by TylerPalko** [comment]
![blm (2)](https://user-images.githubusercontent.com/88953270/229264871-308efcc6-ef08-4eed-b303-cc09782b061a.gif)

**Comment by TylerPalko** [comment]
![image](https://user-images.githubusercontent.com/88953270/229264946-58ada4aa-5a82-4db5-99f6-ab94d1a2b28a.png)
